language: php

php:
  - 7.3
  - 7.4

before_install:
  - SYMFONY_DEPENDENCIES=$(cat composer.json | jq '.require | to_entries[] | "\(.key):\(.value)"' | egrep -o '(symfony\/[^:]+)[^|]+\|' | egrep -o '(symfony\/[^:]+)'); for SYMFONY_DEPENDENCY in $SYMFONY_DEPENDENCIES; do composer require "${SYMFONY_DEPENDENCY}:${SYMFONY_VERSION}" --no-update; done

install: composer install --no-interaction

script:
  - composer run-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=a733f5978a455320d3a02a57f36137697361d096778d6b72cb6176f46d11270a
    - SYMFONY_VERSION=^4.3

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=^3.4
    - php: 7.4
      env: SYMFONY_VERSION=^3.4

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: OymJ4mIeqspGbJkFATRVHb2gxWlT20my/lmcB6cXNAzboHprPD2JMV4S1/9eeOV8km1i6Zl+w8WhIOX+X7x0UW6lk2/ygFx7jRIcyVqIikpbs0/sX1Wte1mcqSS+lqv7fiMc7KR4fgw/IbaJQREoLbywisZ379VGcJiVxwFgIJL/ekKyxftgf2NSgz/qsg88XYOvjK+AyVo+aCPAAiOMsMJD50cIiPzHyic5vNjYqCTOiJQFbuTIF+lUKEOHpck/0pHD9ZkDXTBuDhhUzWZ4xEq7n10JYhFRUIPRWsMZP5yc8R531oEMzUOyq7VdeAhK3+bqiouuZRIXp5FwBKzNdGCI3vHK+aQmZgHKGUVRkze1la+sZzapf2/eWxmsuuEPzxlyxXwWdAoMSvNO79++fEIEugKjPGWkVFg1dsiKlly22l5SLWeqfF7yxukNwCQcjv93qxGi6WGAl1LNm4aKDf3zqGPfe7KOkPCUa0+65ItLXMUmQ0VAoI/rw4yevHMqfXHio0hisKfVpAreQAl2WXlafnI/V8puUetkHr7Uyp1A532/NvnmVihAdsgNncmnhXh96Mb9vtOHQat4XpSTbxn4p/Z3FDu/Zhj48AWW1HRSOnuPs5/vc43T5TW1RpL5ABOs5UtkQDpMO5jj9ZK1lojMYFSgs7FqlYXf5neezOM=
