services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Comsave\SafeSalesforceSaverBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception}'

    old_sound_rabbit_mq.parallel_rpc: '@OldSound\RabbitMqBundle\RabbitMq\RpcClient'

    OldSound\RabbitMqBundle\RabbitMq\RpcClient:
        autowire: false

    Comsave\SafeSalesforceSaverBundle\Producer\AsyncSfSaverProducer: '@old_sound_rabbit_mq.sss_async_processor_producer'