services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Comsave\SafeSalesforceSaverBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception}'

    OldSound\RabbitMqBundle\RabbitMq\RpcClient:
        autowire: true